spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://webtoon-db.cbqivcjiws3r.ap-northeast-2.rds.amazonaws.com:3306/webtoon_database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: hwany
        password: dbghks3655

    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    session:
        store-type: jdbc
        jdbc:
            initialize-schema: always